export enum USER_ACTIONS {
  GET = 'GET_USER',
  GET_SUCCESS = 'GET_USER_SUCCESS',
  SAVE = 'SAVE_USER',
  SAVE_SUCCESS = 'SAVE_USER_SUCCESS',
  DELETE = 'DELETE_USER',
  DELETE_SUCCESS = 'DELETE_USER_SUCCESS',
  UPDATE = 'UPDATE_USER',
  UPDATE_SUCCESS = 'UPDATE_USER_SUCCESS',
}
